/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module x30_gpio_bridge(clk, reset_n, x30_write_enable, x30_write_data, system_armed, enclosure_open, tamper_detected, alarm_reset, x30_read_data, sos_request, local_alarm, alert_led, armed_led);
  input alarm_reset;
  wire alarm_reset;
  output alert_led;
  wire alert_led;
  output armed_led;
  wire armed_led;
  input clk;
  wire clk;
  input enclosure_open;
  wire enclosure_open;
  output local_alarm;
  wire local_alarm;
  wire [3:0] output_register;
  input reset_n;
  wire reset_n;
  output sos_request;
  wire sos_request;
  input system_armed;
  wire system_armed;
  input tamper_detected;
  wire tamper_detected;
  output [31:0] x30_read_data;
  wire [31:0] x30_read_data;
  input [31:0] x30_write_data;
  wire [31:0] x30_write_data;
  input x30_write_enable;
  wire x30_write_enable;
  \$_DFFE_PN0P_  \output_register_reg[0]  /* _0_ */ (
    .C(clk),
    .D(x30_write_data[0]),
    .E(x30_write_enable),
    .Q(output_register[0]),
    .R(reset_n)
  );
  \$_DFFE_PN0P_  \output_register_reg[1]  /* _1_ */ (
    .C(clk),
    .D(x30_write_data[1]),
    .E(x30_write_enable),
    .Q(output_register[1]),
    .R(reset_n)
  );
  \$_DFFE_PN0P_  \output_register_reg[2]  /* _2_ */ (
    .C(clk),
    .D(x30_write_data[2]),
    .E(x30_write_enable),
    .Q(output_register[2]),
    .R(reset_n)
  );
  \$_DFFE_PN0P_  \output_register_reg[3]  /* _3_ */ (
    .C(clk),
    .D(x30_write_data[3]),
    .E(x30_write_enable),
    .Q(output_register[3]),
    .R(reset_n)
  );
  assign alert_led = output_register[1];
  assign armed_led = output_register[0];
  assign local_alarm = output_register[2];
  assign sos_request = output_register[3];
  assign x30_read_data = { system_armed, enclosure_open, tamper_detected, alarm_reset, 24'h000000, output_register };
endmodule
